/**
 * Occupations data source
 * 341 US occupations with BLS OES 2024 employment/wage data and AI exposure scores
 * AI exposure methodology: composite of Felten et al. (2023), Eloundou et al. / OpenAI (2023),
 * Goldman Sachs (2023), and WEF Future of Jobs 2025 assessments
 *
 * Fields: soc, title, sector, employment, medianWage, meanWage, aiExposure, outlook, education
 */

export const OCCUPATIONS = [
  { soc: "11-1011", title: "Chief Executives", sector: "Management", employment: 195560, medianWage: 189520, aiExposure: 7.2, outlook: "Average", education: "Bachelor's" },
  { soc: "11-1021", title: "General and Operations Managers", sector: "Management", employment: 3200540, medianWage: 97970, aiExposure: 6.8, outlook: "Average", education: "Bachelor's" },
  { soc: "11-2021", title: "Marketing Managers", sector: "Management", employment: 315020, medianWage: 140040, aiExposure: 7.4, outlook: "Average", education: "Bachelor's" },
  { soc: "11-2022", title: "Sales Managers", sector: "Management", employment: 389510, medianWage: 130600, aiExposure: 6.5, outlook: "Average", education: "Bachelor's" },
  { soc: "11-3012", title: "Administrative Services Managers", sector: "Management", employment: 287350, medianWage: 101870, aiExposure: 6.2, outlook: "Average", education: "Bachelor's" },
  { soc: "11-3031", title: "Financial Managers", sector: "Management", employment: 681840, medianWage: 139790, aiExposure: 7.1, outlook: "Faster", education: "Bachelor's" },
  { soc: "11-3051", title: "Industrial Production Managers", sector: "Management", employment: 181620, medianWage: 108460, aiExposure: 5.8, outlook: "Average", education: "Bachelor's" },
  { soc: "11-3061", title: "Purchasing Managers", sector: "Management", employment: 71420, medianWage: 127450, aiExposure: 7.6, outlook: "Decline", education: "Bachelor's" },
  { soc: "11-3121", title: "Human Resources Managers", sector: "Management", employment: 161650, medianWage: 126230, aiExposure: 6.9, outlook: "Average", education: "Bachelor's" },
  { soc: "11-9013", title: "Farmers, Ranchers, and Other Agricultural Managers", sector: "Agriculture", employment: 883820, medianWage: 75760, aiExposure: 2.4, outlook: "Decline", education: "High school" },
  { soc: "11-9021", title: "Construction Managers", sector: "Construction", employment: 471010, medianWage: 98890, aiExposure: 4.8, outlook: "Average", education: "Bachelor's" },
  { soc: "11-9041", title: "Architectural and Engineering Managers", sector: "Engineering", employment: 189380, medianWage: 159920, aiExposure: 5.9, outlook: "Average", education: "Bachelor's" },
  { soc: "11-9111", title: "Medical and Health Services Managers", sector: "Healthcare", employment: 509500, medianWage: 104830, aiExposure: 5.6, outlook: "Much faster", education: "Bachelor's" },
  { soc: "11-9141", title: "Property, Real Estate, and Community Association Managers", sector: "Real Estate", employment: 300570, medianWage: 59230, aiExposure: 5.4, outlook: "Average", education: "High school" },
  { soc: "13-1020", title: "Buyers and Purchasing Agents", sector: "Business", employment: 490710, medianWage: 67620, aiExposure: 8.1, outlook: "Decline", education: "Bachelor's" },
  { soc: "13-1041", title: "Compliance Officers", sector: "Business", employment: 347640, medianWage: 73060, aiExposure: 7.3, outlook: "Average", education: "Bachelor's" },
  { soc: "13-1051", title: "Cost Estimators", sector: "Business", employment: 194480, medianWage: 68080, aiExposure: 7.8, outlook: "Average", education: "Bachelor's" },
  { soc: "13-1071", title: "Human Resources Specialists", sector: "Business", employment: 844250, medianWage: 64240, aiExposure: 7.2, outlook: "Average", education: "Bachelor's" },
  { soc: "13-1081", title: "Logisticians", sector: "Business", employment: 182770, medianWage: 77030, aiExposure: 7.5, outlook: "Faster", education: "Bachelor's" },
  { soc: "13-1111", title: "Management Analysts", sector: "Business", employment: 806620, medianWage: 93000, aiExposure: 8.3, outlook: "Faster", education: "Bachelor's" },
  { soc: "13-1121", title: "Meeting, Convention, and Event Planners", sector: "Business", employment: 136350, medianWage: 51560, aiExposure: 5.7, outlook: "Faster", education: "Bachelor's" },
  { soc: "13-1141", title: "Compensation, Benefits, and Job Analysis Specialists", sector: "Business", employment: 80310, medianWage: 65040, aiExposure: 8.0, outlook: "Average", education: "Bachelor's" },
  { soc: "13-1151", title: "Training and Development Specialists", sector: "Business", employment: 345620, medianWage: 62700, aiExposure: 6.8, outlook: "Faster", education: "Bachelor's" },
  { soc: "13-2011", title: "Accountants and Auditors", sector: "Finance", employment: 1356000, medianWage: 77250, aiExposure: 8.6, outlook: "Average", education: "Bachelor's" },
  { soc: "13-2041", title: "Credit Analysts", sector: "Finance", employment: 82040, medianWage: 73650, aiExposure: 8.4, outlook: "Decline", education: "Bachelor's" },
  { soc: "13-2051", title: "Financial and Investment Analysts", sector: "Finance", employment: 330620, medianWage: 95570, aiExposure: 8.9, outlook: "Faster", education: "Bachelor's" },
  { soc: "13-2052", title: "Personal Financial Advisors", sector: "Finance", employment: 263200, medianWage: 95390, aiExposure: 6.9, outlook: "Faster", education: "Bachelor's" },
  { soc: "13-2061", title: "Financial Examiners", sector: "Finance", employment: 60780, medianWage: 81410, aiExposure: 7.7, outlook: "Faster", education: "Bachelor's" },
  { soc: "13-2070", title: "Credit Counselors and Loan Officers", sector: "Finance", employment: 328640, medianWage: 65740, aiExposure: 7.8, outlook: "Average", education: "Bachelor's" },
  { soc: "13-2099", title: "Financial Specialists, All Other", sector: "Finance", employment: 117520, medianWage: 72450, aiExposure: 7.9, outlook: "Average", education: "Bachelor's" },
  { soc: "15-1211", title: "Computer Systems Analysts", sector: "Technology", employment: 545280, medianWage: 99270, aiExposure: 8.2, outlook: "Average", education: "Bachelor's" },
  { soc: "15-1212", title: "Information Security Analysts", sector: "Technology", employment: 163680, medianWage: 112000, aiExposure: 6.4, outlook: "Much faster", education: "Bachelor's" },
  { soc: "15-1221", title: "Computer and Information Research Scientists", sector: "Technology", employment: 33870, medianWage: 131490, aiExposure: 7.8, outlook: "Much faster", education: "Master's" },
  { soc: "15-1231", title: "Computer Network Support Specialists", sector: "Technology", employment: 170040, medianWage: 57910, aiExposure: 6.9, outlook: "Average", education: "Some college" },
  { soc: "15-1232", title: "Computer User Support Specialists", sector: "Technology", employment: 626190, medianWage: 57910, aiExposure: 7.2, outlook: "Average", education: "Some college" },
  { soc: "15-1241", title: "Computer Network Architects", sector: "Technology", employment: 155690, medianWage: 120520, aiExposure: 6.7, outlook: "Decline", education: "Bachelor's" },
  { soc: "15-1242", title: "Database Administrators", sector: "Technology", employment: 107900, medianWage: 98860, aiExposure: 7.8, outlook: "Faster", education: "Bachelor's" },
  { soc: "15-1243", title: "Database Architects", sector: "Technology", employment: 132610, medianWage: 114400, aiExposure: 7.6, outlook: "Faster", education: "Bachelor's" },
  { soc: "15-1244", title: "Network and Computer Systems Administrators", sector: "Technology", employment: 281760, medianWage: 87070, aiExposure: 6.8, outlook: "Decline", education: "Bachelor's" },
  { soc: "15-1251", title: "Computer Programmers", sector: "Technology", employment: 152960, medianWage: 97800, aiExposure: 9.1, outlook: "Decline", education: "Bachelor's" },
  { soc: "15-1252", title: "Software Developers", sector: "Technology", employment: 1682110, medianWage: 127260, aiExposure: 8.7, outlook: "Much faster", education: "Bachelor's" },
  { soc: "15-1253", title: "Software Quality Assurance Analysts and Testers", sector: "Technology", employment: 229160, medianWage: 97700, aiExposure: 8.8, outlook: "Much faster", education: "Bachelor's" },
  { soc: "15-1254", title: "Web Developers", sector: "Technology", employment: 181870, medianWage: 78300, aiExposure: 8.5, outlook: "Faster", education: "Associate's" },
  { soc: "15-1255", title: "Web and Digital Interface Designers", sector: "Technology", employment: 205880, medianWage: 83240, aiExposure: 8.2, outlook: "Faster", education: "Bachelor's" },
  { soc: "15-2011", title: "Actuaries", sector: "Mathematics", employment: 27700, medianWage: 113990, aiExposure: 8.5, outlook: "Much faster", education: "Bachelor's" },
  { soc: "15-2021", title: "Mathematicians", sector: "Mathematics", employment: 3100, medianWage: 112110, aiExposure: 6.4, outlook: "Much faster", education: "Master's" },
  { soc: "15-2031", title: "Operations Research Analysts", sector: "Mathematics", employment: 118940, medianWage: 83380, aiExposure: 8.7, outlook: "Much faster", education: "Bachelor's" },
  { soc: "15-2041", title: "Statisticians", sector: "Mathematics", employment: 45630, medianWage: 99960, aiExposure: 8.3, outlook: "Much faster", education: "Master's" },
  { soc: "15-2051", title: "Data Scientists", sector: "Mathematics", employment: 168320, medianWage: 103500, aiExposure: 8.6, outlook: "Much faster", education: "Bachelor's" },
  { soc: "17-1011", title: "Architects, Except Landscape and Naval", sector: "Architecture", employment: 112090, medianWage: 82320, aiExposure: 6.8, outlook: "Average", education: "Bachelor's" },
  { soc: "17-1012", title: "Landscape Architects", sector: "Architecture", employment: 21080, medianWage: 70630, aiExposure: 5.4, outlook: "Average", education: "Bachelor's" },
  { soc: "17-1022", title: "Surveyors", sector: "Architecture", employment: 44490, medianWage: 61590, aiExposure: 4.9, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2011", title: "Aerospace Engineers", sector: "Engineering", employment: 66690, medianWage: 122270, aiExposure: 6.2, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2041", title: "Chemical Engineers", sector: "Engineering", employment: 24630, medianWage: 105550, aiExposure: 6.5, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2051", title: "Civil Engineers", sector: "Engineering", employment: 329270, medianWage: 88050, aiExposure: 5.7, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2061", title: "Computer Hardware Engineers", sector: "Engineering", employment: 71300, medianWage: 128170, aiExposure: 7.4, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2071", title: "Electrical Engineers", sector: "Engineering", employment: 188060, medianWage: 100420, aiExposure: 6.8, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2072", title: "Electronics Engineers, Except Computer", sector: "Engineering", employment: 126420, medianWage: 107540, aiExposure: 6.6, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2081", title: "Environmental Engineers", sector: "Engineering", employment: 56670, medianWage: 94220, aiExposure: 5.8, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2112", title: "Industrial Engineers", sector: "Engineering", employment: 292250, medianWage: 95300, aiExposure: 7.3, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2141", title: "Mechanical Engineers", sector: "Engineering", employment: 290830, medianWage: 95300, aiExposure: 6.9, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2161", title: "Nuclear Engineers", sector: "Engineering", employment: 16680, medianWage: 120380, aiExposure: 5.9, outlook: "Average", education: "Bachelor's" },
  { soc: "17-2171", title: "Petroleum Engineers", sector: "Engineering", employment: 32260, medianWage: 130850, aiExposure: 6.2, outlook: "Average", education: "Bachelor's" },
  { soc: "17-3011", title: "Architectural and Civil Drafters", sector: "Engineering", employment: 79320, medianWage: 57280, aiExposure: 8.1, outlook: "Decline", education: "Associate's" },
  { soc: "17-3013", title: "Mechanical Drafters", sector: "Engineering", employment: 62640, medianWage: 57460, aiExposure: 8.3, outlook: "Decline", education: "Associate's" },
  { soc: "19-1011", title: "Animal Scientists", sector: "Life Sciences", employment: 6140, medianWage: 67810, aiExposure: 4.2, outlook: "Average", education: "Doctoral" },
  { soc: "19-1020", title: "Biological Scientists", sector: "Life Sciences", employment: 34190, medianWage: 82870, aiExposure: 5.8, outlook: "Faster", education: "Doctoral" },
  { soc: "19-1031", title: "Conservation Scientists and Foresters", sector: "Life Sciences", employment: 42230, medianWage: 64750, aiExposure: 3.9, outlook: "Average", education: "Bachelor's" },
  { soc: "19-1042", title: "Medical Scientists, Except Epidemiologists", sector: "Life Sciences", employment: 140340, medianWage: 95310, aiExposure: 6.4, outlook: "Faster", education: "Doctoral" },
  { soc: "19-2011", title: "Astronomers and Physicists", sector: "Physical Sciences", employment: 22300, medianWage: 137950, aiExposure: 6.1, outlook: "Faster", education: "Doctoral" },
  { soc: "19-2031", title: "Chemists and Materials Scientists", sector: "Physical Sciences", employment: 88780, medianWage: 80760, aiExposure: 5.7, outlook: "Average", education: "Bachelor's" },
  { soc: "19-2041", title: "Environmental Scientists and Specialists", sector: "Physical Sciences", employment: 90310, medianWage: 76480, aiExposure: 5.3, outlook: "Faster", education: "Bachelor's" },
  { soc: "19-2099", title: "Physical Scientists, All Other", sector: "Physical Sciences", employment: 30760, medianWage: 102040, aiExposure: 5.6, outlook: "Average", education: "Master's" },
  { soc: "19-3011", title: "Economists", sector: "Social Sciences", employment: 22540, medianWage: 113940, aiExposure: 8.2, outlook: "Faster", education: "Master's" },
  { soc: "19-3031", title: "Clinical and Counseling Psychologists", sector: "Social Sciences", employment: 123840, medianWage: 82510, aiExposure: 4.1, outlook: "Faster", education: "Doctoral" },
  { soc: "19-3041", title: "Sociologists", sector: "Social Sciences", employment: 3590, medianWage: 92910, aiExposure: 6.3, outlook: "Average", education: "Master's" },
  { soc: "19-3051", title: "Urban and Regional Planners", sector: "Social Sciences", employment: 41710, medianWage: 78040, aiExposure: 6.1, outlook: "Faster", education: "Master's" },
  { soc: "19-3091", title: "Anthropologists and Archeologists", sector: "Social Sciences", employment: 8030, medianWage: 63940, aiExposure: 4.7, outlook: "Average", education: "Master's" },
  { soc: "19-4012", title: "Agricultural Technicians", sector: "Life Sciences", employment: 32290, medianWage: 43590, aiExposure: 3.8, outlook: "Average", education: "Associate's" },
  { soc: "19-4021", title: "Biological Technicians", sector: "Life Sciences", employment: 79680, medianWage: 48810, aiExposure: 4.2, outlook: "Average", education: "Bachelor's" },
  { soc: "19-4031", title: "Chemical Technicians", sector: "Physical Sciences", employment: 59380, medianWage: 50900, aiExposure: 5.1, outlook: "Average", education: "Associate's" },
  { soc: "21-1011", title: "Substance Abuse and Behavioral Disorder Counselors", sector: "Healthcare", employment: 361050, medianWage: 49710, aiExposure: 3.2, outlook: "Much faster", education: "Bachelor's" },
  { soc: "21-1012", title: "Educational, Guidance, and Career Counselors", sector: "Education", employment: 341080, medianWage: 60510, aiExposure: 4.4, outlook: "Average", education: "Master's" },
  { soc: "21-1021", title: "Child, Family, and School Social Workers", sector: "Social Services", employment: 338780, medianWage: 50820, aiExposure: 2.8, outlook: "Average", education: "Bachelor's" },
  { soc: "21-1022", title: "Healthcare Social Workers", sector: "Healthcare", employment: 195490, medianWage: 60840, aiExposure: 3.1, outlook: "Faster", education: "Master's" },
  { soc: "21-1023", title: "Mental Health and Substance Abuse Social Workers", sector: "Healthcare", employment: 137680, medianWage: 51430, aiExposure: 3.4, outlook: "Faster", education: "Master's" },
  { soc: "21-1029", title: "Social Workers, All Other", sector: "Social Services", employment: 73870, medianWage: 56730, aiExposure: 3.3, outlook: "Average", education: "Bachelor's" },
  { soc: "21-1091", title: "Health Education Specialists", sector: "Healthcare", employment: 64150, medianWage: 60600, aiExposure: 4.6, outlook: "Faster", education: "Bachelor's" },
  { soc: "21-2011", title: "Clergy", sector: "Religious", employment: 49840, medianWage: 57230, aiExposure: 1.8, outlook: "Average", education: "Master's" },
  { soc: "23-1011", title: "Lawyers", sector: "Legal", employment: 803490, medianWage: 127990, aiExposure: 7.9, outlook: "Average", education: "Doctoral" },
  { soc: "23-1012", title: "Judicial Law Clerks", sector: "Legal", employment: 29390, medianWage: 55870, aiExposure: 8.4, outlook: "Average", education: "Doctoral" },
  { soc: "23-2011", title: "Paralegals and Legal Assistants", sector: "Legal", employment: 347530, medianWage: 59200, aiExposure: 8.7, outlook: "Faster", education: "Associate's" },
  { soc: "23-2093", title: "Title Examiners, Abstractors, and Searchers", sector: "Legal", employment: 52970, medianWage: 50040, aiExposure: 8.5, outlook: "Decline", education: "High school" },
  { soc: "25-1000", title: "Postsecondary Teachers", sector: "Education", employment: 1360920, medianWage: 80840, aiExposure: 5.6, outlook: "Faster", education: "Doctoral" },
  { soc: "25-2011", title: "Preschool Teachers", sector: "Education", employment: 540810, medianWage: 35430, aiExposure: 1.6, outlook: "Average", education: "Associate's" },
  { soc: "25-2021", title: "Elementary School Teachers", sector: "Education", employment: 1494100, medianWage: 63280, aiExposure: 2.4, outlook: "Average", education: "Bachelor's" },
  { soc: "25-2022", title: "Middle School Teachers", sector: "Education", employment: 624580, medianWage: 64990, aiExposure: 2.6, outlook: "Average", education: "Bachelor's" },
  { soc: "25-2031", title: "Secondary School Teachers", sector: "Education", employment: 1056020, medianWage: 66520, aiExposure: 2.7, outlook: "Average", education: "Bachelor's" },
  { soc: "25-2052", title: "Special Education Teachers", sector: "Education", employment: 475720, medianWage: 61820, aiExposure: 1.9, outlook: "Average", education: "Bachelor's" },
  { soc: "25-3021", title: "Self-Enrichment Teachers", sector: "Education", employment: 369420, medianWage: 42490, aiExposure: 2.9, outlook: "Faster", education: "High school" },
  { soc: "25-4012", title: "Librarians and Media Collections Specialists", sector: "Education", employment: 148630, medianWage: 61660, aiExposure: 7.1, outlook: "Decline", education: "Master's" },
  { soc: "25-4022", title: "Library Technicians", sector: "Education", employment: 97330, medianWage: 36050, aiExposure: 7.4, outlook: "Decline", education: "Some college" },
  { soc: "25-9031", title: "Instructional Coordinators", sector: "Education", employment: 179860, medianWage: 66970, aiExposure: 6.2, outlook: "Average", education: "Master's" },
  { soc: "27-1011", title: "Art Directors", sector: "Arts", employment: 86290, medianWage: 100890, aiExposure: 7.6, outlook: "Average", education: "Bachelor's" },
  { soc: "27-1013", title: "Fine Artists, Including Painters, Sculptors, and Illustrators", sector: "Arts", employment: 30970, medianWage: 55840, aiExposure: 6.8, outlook: "Average", education: "Bachelor's" },
  { soc: "27-1014", title: "Special Effects Artists and Animators", sector: "Arts", employment: 75540, medianWage: 78790, aiExposure: 8.4, outlook: "Average", education: "Bachelor's" },
  { soc: "27-1021", title: "Commercial and Industrial Designers", sector: "Arts", employment: 38690, medianWage: 68890, aiExposure: 7.8, outlook: "Average", education: "Bachelor's" },
  { soc: "27-1022", title: "Fashion Designers", sector: "Arts", employment: 17330, medianWage: 77450, aiExposure: 7.2, outlook: "Average", education: "Bachelor's" },
  { soc: "27-1024", title: "Graphic Designers", sector: "Arts", employment: 268700, medianWage: 57990, aiExposure: 8.5, outlook: "Decline", education: "Bachelor's" },
  { soc: "27-1025", title: "Interior Designers", sector: "Arts", employment: 78980, medianWage: 61590, aiExposure: 6.9, outlook: "Average", education: "Bachelor's" },
  { soc: "27-2011", title: "Actors", sector: "Entertainment", employment: 63880, medianWage: 46960, aiExposure: 5.7, outlook: "Average", education: "High school" },
  { soc: "27-2012", title: "Producers and Directors", sector: "Entertainment", employment: 178820, medianWage: 79000, aiExposure: 6.8, outlook: "Faster", education: "Bachelor's" },
  { soc: "27-2022", title: "Coaches and Scouts", sector: "Entertainment", employment: 320970, medianWage: 44350, aiExposure: 2.1, outlook: "Faster", education: "Bachelor's" },
  { soc: "27-2023", title: "Umpires, Referees, and Other Sports Officials", sector: "Entertainment", employment: 22290, medianWage: 30430, aiExposure: 1.9, outlook: "Average", education: "High school" },
  { soc: "27-2041", title: "Music Directors and Composers", sector: "Entertainment", employment: 73700, medianWage: 59940, aiExposure: 6.2, outlook: "Average", education: "Bachelor's" },
  { soc: "27-2042", title: "Musicians and Singers", sector: "Entertainment", employment: 172090, medianWage: 33870, aiExposure: 5.8, outlook: "Average", education: "High school" },
  { soc: "27-3011", title: "Broadcast Announcers and Radio Disc Jockeys", sector: "Media", employment: 35640, medianWage: 48890, aiExposure: 7.8, outlook: "Decline", education: "Bachelor's" },
  { soc: "27-3023", title: "News Analysts, Reporters, and Journalists", sector: "Media", employment: 57260, medianWage: 55960, aiExposure: 8.6, outlook: "Decline", education: "Bachelor's" },
  { soc: "27-3031", title: "Public Relations Specialists", sector: "Media", employment: 267430, medianWage: 67440, aiExposure: 7.4, outlook: "Average", education: "Bachelor's" },
  { soc: "27-3041", title: "Editors", sector: "Media", employment: 127360, medianWage: 73080, aiExposure: 8.7, outlook: "Decline", education: "Bachelor's" },
  { soc: "27-3042", title: "Technical Writers", sector: "Media", employment: 56890, medianWage: 78060, aiExposure: 8.9, outlook: "Average", education: "Bachelor's" },
  { soc: "27-3043", title: "Writers and Authors", sector: "Media", employment: 146220, medianWage: 73690, aiExposure: 9.0, outlook: "Average", education: "Bachelor's" },
  { soc: "27-3091", title: "Interpreters and Translators", sector: "Media", employment: 80550, medianWage: 53640, aiExposure: 9.2, outlook: "Faster", education: "Bachelor's" },
  { soc: "27-4011", title: "Audio and Video Technicians", sector: "Media", employment: 136480, medianWage: 49230, aiExposure: 5.8, outlook: "Faster", education: "Associate's" },
  { soc: "27-4021", title: "Photographers", sector: "Media", employment: 140920, medianWage: 40170, aiExposure: 7.3, outlook: "Average", education: "High school" },
  { soc: "29-1020", title: "Dentists", sector: "Healthcare", employment: 112820, medianWage: 159530, aiExposure: 3.5, outlook: "Average", education: "Doctoral" },
  { soc: "29-1041", title: "Optometrists", sector: "Healthcare", employment: 46840, medianWage: 115250, aiExposure: 4.2, outlook: "Faster", education: "Doctoral" },
  { soc: "29-1051", title: "Pharmacists", sector: "Healthcare", employment: 320730, medianWage: 132750, aiExposure: 5.9, outlook: "Decline", education: "Doctoral" },
  { soc: "29-1071", title: "Physician Assistants", sector: "Healthcare", employment: 142610, medianWage: 126010, aiExposure: 4.8, outlook: "Much faster", education: "Master's" },
  { soc: "29-1141", title: "Registered Nurses", sector: "Healthcare", employment: 3130600, medianWage: 81220, aiExposure: 3.6, outlook: "Faster", education: "Bachelor's" },
  { soc: "29-1151", title: "Nurse Anesthetists", sector: "Healthcare", employment: 43700, medianWage: 203090, aiExposure: 3.1, outlook: "Much faster", education: "Master's" },
  { soc: "29-1171", title: "Nurse Practitioners", sector: "Healthcare", employment: 246340, medianWage: 124680, aiExposure: 4.3, outlook: "Much faster", education: "Master's" },
  { soc: "29-1210", title: "Physicians", sector: "Healthcare", employment: 713800, medianWage: 229300, aiExposure: 5.1, outlook: "Average", education: "Doctoral" },
  { soc: "29-1224", title: "Radiologists", sector: "Healthcare", employment: 25800, medianWage: 329570, aiExposure: 7.8, outlook: "Average", education: "Doctoral" },
  { soc: "29-2011", title: "Medical and Clinical Laboratory Technologists and Technicians", sector: "Healthcare", employment: 335410, medianWage: 57380, aiExposure: 6.2, outlook: "Faster", education: "Associate's" },
  { soc: "29-2021", title: "Dental Hygienists", sector: "Healthcare", employment: 208100, medianWage: 81400, aiExposure: 3.4, outlook: "Average", education: "Associate's" },
  { soc: "29-2032", title: "Diagnostic Medical Sonographers", sector: "Healthcare", employment: 78040, medianWage: 79520, aiExposure: 5.7, outlook: "Faster", education: "Associate's" },
  { soc: "29-2034", title: "Radiologic Technologists and Technicians", sector: "Healthcare", employment: 222570, medianWage: 65140, aiExposure: 6.4, outlook: "Average", education: "Associate's" },
  { soc: "29-2052", title: "Pharmacy Technicians", sector: "Healthcare", employment: 420400, medianWage: 36940, aiExposure: 7.1, outlook: "Average", education: "High school" },
  { soc: "29-2055", title: "Surgical Technologists", sector: "Healthcare", employment: 117630, medianWage: 54910, aiExposure: 3.8, outlook: "Faster", education: "Associate's" },
  { soc: "29-2061", title: "Licensed Practical and Licensed Vocational Nurses", sector: "Healthcare", employment: 676470, medianWage: 54520, aiExposure: 3.5, outlook: "Average", education: "Certificate" },
  { soc: "31-1120", title: "Home Health and Personal Care Aides", sector: "Healthcare", employment: 3593990, medianWage: 30180, aiExposure: 1.4, outlook: "Much faster", education: "High school" },
  { soc: "31-2011", title: "Occupational Therapy Assistants and Aides", sector: "Healthcare", employment: 53450, medianWage: 63840, aiExposure: 2.8, outlook: "Much faster", education: "Associate's" },
  { soc: "31-2021", title: "Physical Therapist Assistants and Aides", sector: "Healthcare", employment: 124660, medianWage: 61180, aiExposure: 2.4, outlook: "Much faster", education: "Associate's" },
  { soc: "33-1011", title: "First-Line Supervisors of Correctional Officers", sector: "Protective Services", employment: 44320, medianWage: 74240, aiExposure: 2.6, outlook: "Average", education: "High school" },
  { soc: "33-1021", title: "First-Line Supervisors of Firefighting and Prevention Workers", sector: "Protective Services", employment: 79290, medianWage: 79560, aiExposure: 2.3, outlook: "Average", education: "High school" },
  { soc: "33-1051", title: "Police and Detectives, Supervisors", sector: "Protective Services", employment: 118400, medianWage: 97160, aiExposure: 3.1, outlook: "Average", education: "High school" },
  { soc: "33-2011", title: "Firefighters", sector: "Protective Services", employment: 318560, medianWage: 52500, aiExposure: 1.7, outlook: "Average", education: "High school" },
  { soc: "33-3012", title: "Correctional Officers and Jailers", sector: "Protective Services", employment: 376480, medianWage: 49610, aiExposure: 2.2, outlook: "Decline", education: "High school" },
  { soc: "33-3021", title: "Detectives and Criminal Investigators", sector: "Protective Services", employment: 114970, medianWage: 86940, aiExposure: 4.9, outlook: "Average", education: "High school" },
  { soc: "33-3051", title: "Police and Sheriff's Patrol Officers", sector: "Protective Services", employment: 654950, medianWage: 65790, aiExposure: 3.3, outlook: "Average", education: "High school" },
  { soc: "33-9021", title: "Private Detectives and Investigators", sector: "Protective Services", employment: 38570, medianWage: 59380, aiExposure: 5.8, outlook: "Faster", education: "High school" },
  { soc: "33-9032", title: "Security Guards and Gambling Surveillance Officers", sector: "Protective Services", employment: 1131590, medianWage: 34470, aiExposure: 4.7, outlook: "Average", education: "High school" },
  { soc: "35-1011", title: "Chefs and Head Cooks", sector: "Food Service", employment: 152480, medianWage: 56520, aiExposure: 2.1, outlook: "Faster", education: "High school" },
  { soc: "35-1012", title: "First-Line Supervisors of Food Preparation and Serving Workers", sector: "Food Service", employment: 964200, medianWage: 37290, aiExposure: 3.2, outlook: "Average", education: "High school" },
  { soc: "35-2014", title: "Cooks, Restaurant", sector: "Food Service", employment: 1308290, medianWage: 31100, aiExposure: 2.8, outlook: "Average", education: "High school" },
  { soc: "35-3023", title: "Fast Food and Counter Workers", sector: "Food Service", employment: 3712040, medianWage: 28730, aiExposure: 5.3, outlook: "Average", education: "High school" },
  { soc: "35-3031", title: "Waiters and Waitresses", sector: "Food Service", employment: 2289770, medianWage: 29120, aiExposure: 4.1, outlook: "Average", education: "High school" },
  { soc: "35-9021", title: "Dishwashers", sector: "Food Service", employment: 393850, medianWage: 27070, aiExposure: 3.6, outlook: "Average", education: "High school" },
  { soc: "37-1011", title: "First-Line Supervisors of Housekeeping and Janitorial Workers", sector: "Maintenance", employment: 185650, medianWage: 47750, aiExposure: 2.8, outlook: "Average", education: "High school" },
  { soc: "37-2011", title: "Janitors and Cleaners, Except Maids and Housekeeping Cleaners", sector: "Maintenance", employment: 2175320, medianWage: 33050, aiExposure: 2.1, outlook: "Average", education: "High school" },
  { soc: "37-2012", title: "Maids and Housekeeping Cleaners", sector: "Maintenance", employment: 903270, medianWage: 29940, aiExposure: 2.3, outlook: "Average", education: "High school" },
  { soc: "37-3011", title: "Landscaping and Groundskeeping Workers", sector: "Agriculture", employment: 1198690, medianWage: 34230, aiExposure: 1.8, outlook: "Average", education: "High school" },
  { soc: "39-1013", title: "First-Line Supervisors of Gambling Services Workers", sector: "Personal Services", employment: 39050, medianWage: 59470, aiExposure: 3.4, outlook: "Average", education: "High school" },
  { soc: "39-2021", title: "Animal Trainers", sector: "Personal Services", employment: 59940, medianWage: 34980, aiExposure: 2.0, outlook: "Faster", education: "High school" },
  { soc: "39-3031", title: "Gambling Dealers", sector: "Personal Services", employment: 98840, medianWage: 31730, aiExposure: 4.2, outlook: "Average", education: "High school" },
  { soc: "39-4011", title: "Embalmers and Funeral Attendants", sector: "Personal Services", employment: 30810, medianWage: 46020, aiExposure: 2.3, outlook: "Average", education: "Associate's" },
  { soc: "39-5011", title: "Barbers", sector: "Personal Services", employment: 86370, medianWage: 33810, aiExposure: 1.4, outlook: "Average", education: "Certificate" },
  { soc: "39-5012", title: "Hairdressers, Hairstylists, and Cosmetologists", sector: "Personal Services", employment: 641600, medianWage: 33400, aiExposure: 1.6, outlook: "Average", education: "Certificate" },
  { soc: "39-5091", title: "Makeup Artists, Theatrical and Performance", sector: "Personal Services", employment: 13490, medianWage: 97910, aiExposure: 3.1, outlook: "Average", education: "Certificate" },
  { soc: "39-5093", title: "Shampooers", sector: "Personal Services", employment: 12680, medianWage: 24430, aiExposure: 1.2, outlook: "Decline", education: "High school" },
  { soc: "39-5094", title: "Skincare Specialists", sector: "Personal Services", employment: 75970, medianWage: 39810, aiExposure: 2.2, outlook: "Much faster", education: "Certificate" },
  { soc: "39-6011", title: "Concierges", sector: "Personal Services", employment: 45290, medianWage: 35990, aiExposure: 5.6, outlook: "Average", education: "High school" },
  { soc: "39-7011", title: "Tour and Travel Guides", sector: "Personal Services", employment: 25480, medianWage: 32720, aiExposure: 5.1, outlook: "Faster", education: "High school" },
  { soc: "39-9011", title: "Childcare Workers", sector: "Personal Services", employment: 526170, medianWage: 28520, aiExposure: 1.5, outlook: "Average", education: "High school" },
  { soc: "39-9021", title: "Personal Care and Service Workers", sector: "Personal Services", employment: 119590, medianWage: 28240, aiExposure: 1.8, outlook: "Faster", education: "High school" },
  { soc: "41-1011", title: "First-Line Supervisors of Retail Sales Workers", sector: "Sales", employment: 1246370, medianWage: 44660, aiExposure: 4.6, outlook: "Average", education: "High school" },
  { soc: "41-2011", title: "Cashiers", sector: "Sales", employment: 3368240, medianWage: 28630, aiExposure: 7.9, outlook: "Decline", education: "High school" },
  { soc: "41-2021", title: "Counter and Rental Clerks", sector: "Sales", employment: 460820, medianWage: 33060, aiExposure: 6.8, outlook: "Decline", education: "High school" },
  { soc: "41-2031", title: "Retail Salespersons", sector: "Sales", employment: 4265350, medianWage: 30030, aiExposure: 5.9, outlook: "Decline", education: "High school" },
  { soc: "41-3011", title: "Advertising Sales Agents", sector: "Sales", employment: 152300, medianWage: 56290, aiExposure: 7.4, outlook: "Decline", education: "Bachelor's" },
  { soc: "41-3021", title: "Insurance Sales Agents", sector: "Sales", employment: 546540, medianWage: 57860, aiExposure: 7.6, outlook: "Average", education: "Bachelor's" },
  { soc: "41-3031", title: "Securities, Commodities, and Financial Services Sales Agents", sector: "Sales", employment: 476060, medianWage: 67480, aiExposure: 7.8, outlook: "Average", education: "Bachelor's" },
  { soc: "41-3041", title: "Travel Agents", sector: "Sales", employment: 67870, medianWage: 46400, aiExposure: 8.1, outlook: "Average", education: "High school" },
  { soc: "41-4011", title: "Sales Representatives, Wholesale and Manufacturing, Technical", sector: "Sales", employment: 359280, medianWage: 91430, aiExposure: 6.2, outlook: "Average", education: "Bachelor's" },
  { soc: "41-4012", title: "Sales Representatives, Wholesale and Manufacturing, Nontechnical", sector: "Sales", employment: 1268890, medianWage: 61660, aiExposure: 6.4, outlook: "Average", education: "High school" },
  { soc: "43-1011", title: "First-Line Supervisors of Office and Administrative Support Workers", sector: "Office & Admin", employment: 1442500, medianWage: 60470, aiExposure: 6.7, outlook: "Average", education: "High school" },
  { soc: "43-3011", title: "Bill and Account Collectors", sector: "Office & Admin", employment: 214290, medianWage: 40610, aiExposure: 8.4, outlook: "Decline", education: "High school" },
  { soc: "43-3021", title: "Billing and Posting Clerks", sector: "Office & Admin", employment: 441720, medianWage: 42080, aiExposure: 8.9, outlook: "Decline", education: "High school" },
  { soc: "43-3031", title: "Bookkeeping, Accounting, and Auditing Clerks", sector: "Office & Admin", employment: 1370100, medianWage: 45860, aiExposure: 9.2, outlook: "Decline", education: "High school" },
  { soc: "43-3041", title: "Gambling Cage Workers", sector: "Office & Admin", employment: 19060, medianWage: 33640, aiExposure: 6.3, outlook: "Average", education: "High school" },
  { soc: "43-3051", title: "Payroll and Timekeeping Clerks", sector: "Office & Admin", employment: 157430, medianWage: 47390, aiExposure: 9.0, outlook: "Decline", education: "High school" },
  { soc: "43-3061", title: "Procurement Clerks", sector: "Office & Admin", employment: 63300, medianWage: 46700, aiExposure: 8.8, outlook: "Decline", education: "High school" },
  { soc: "43-3071", title: "Tellers", sector: "Office & Admin", employment: 415900, medianWage: 37890, aiExposure: 8.7, outlook: "Decline", education: "High school" },
  { soc: "43-4051", title: "Customer Service Representatives", sector: "Office & Admin", employment: 2887780, medianWage: 37780, aiExposure: 8.6, outlook: "Decline", education: "High school" },
  { soc: "43-4061", title: "Eligibility Interviewers, Government Programs", sector: "Office & Admin", employment: 107880, medianWage: 47640, aiExposure: 8.2, outlook: "Decline", education: "High school" },
  { soc: "43-4071", title: "File Clerks", sector: "Office & Admin", employment: 162060, medianWage: 37110, aiExposure: 9.1, outlook: "Decline", education: "High school" },
  { soc: "43-4081", title: "Hotel, Motel, and Resort Desk Clerks", sector: "Office & Admin", employment: 200370, medianWage: 30300, aiExposure: 6.8, outlook: "Average", education: "High school" },
  { soc: "43-4111", title: "Interviewers, Except Eligibility and Loan", sector: "Office & Admin", employment: 181600, medianWage: 39670, aiExposure: 8.3, outlook: "Decline", education: "High school" },
  { soc: "43-4121", title: "Library Assistants, Clerical", sector: "Office & Admin", employment: 95830, medianWage: 30700, aiExposure: 7.6, outlook: "Decline", education: "High school" },
  { soc: "43-4141", title: "New Accounts Clerks", sector: "Office & Admin", employment: 44250, medianWage: 39830, aiExposure: 8.7, outlook: "Decline", education: "High school" },
  { soc: "43-4151", title: "Order Clerks", sector: "Office & Admin", employment: 175780, medianWage: 39460, aiExposure: 9.0, outlook: "Decline", education: "High school" },
  { soc: "43-4161", title: "Human Resources Assistants", sector: "Office & Admin", employment: 145610, medianWage: 43990, aiExposure: 8.5, outlook: "Decline", education: "High school" },
  { soc: "43-4171", title: "Receptionists and Information Clerks", sector: "Office & Admin", employment: 1044870, medianWage: 34860, aiExposure: 8.1, outlook: "Decline", education: "High school" },
  { soc: "43-5011", title: "Cargo and Freight Agents", sector: "Office & Admin", employment: 93740, medianWage: 48430, aiExposure: 7.8, outlook: "Average", education: "High school" },
  { soc: "43-5021", title: "Couriers and Messengers", sector: "Office & Admin", employment: 107540, medianWage: 37770, aiExposure: 5.4, outlook: "Average", education: "High school" },
  { soc: "43-5031", title: "Public Safety Telecommunicators", sector: "Office & Admin", employment: 95710, medianWage: 46780, aiExposure: 6.4, outlook: "Average", education: "High school" },
  { soc: "43-5041", title: "Meter Readers, Utilities", sector: "Office & Admin", employment: 24930, medianWage: 43520, aiExposure: 7.2, outlook: "Decline", education: "High school" },
  { soc: "43-5051", title: "Postal Service Clerks", sector: "Office & Admin", employment: 73000, medianWage: 57070, aiExposure: 6.1, outlook: "Decline", education: "High school" },
  { soc: "43-5052", title: "Postal Service Mail Carriers", sector: "Office & Admin", employment: 335870, medianWage: 57840, aiExposure: 5.2, outlook: "Decline", education: "High school" },
  { soc: "43-5061", title: "Production, Planning, and Expediting Clerks", sector: "Office & Admin", employment: 343150, medianWage: 50660, aiExposure: 8.3, outlook: "Average", education: "High school" },
  { soc: "43-5071", title: "Shipping, Receiving, and Inventory Clerks", sector: "Office & Admin", employment: 601830, medianWage: 38640, aiExposure: 7.4, outlook: "Decline", education: "High school" },
  { soc: "43-6011", title: "Executive Secretaries and Executive Administrative Assistants", sector: "Office & Admin", employment: 549340, medianWage: 65980, aiExposure: 8.8, outlook: "Decline", education: "High school" },
  { soc: "43-6014", title: "Secretaries and Administrative Assistants", sector: "Office & Admin", employment: 1968380, medianWage: 42770, aiExposure: 8.9, outlook: "Decline", education: "High school" },
  { soc: "43-9011", title: "Computer Operators", sector: "Office & Admin", employment: 57960, medianWage: 48010, aiExposure: 8.4, outlook: "Decline", education: "High school" },
  { soc: "43-9021", title: "Data Entry Keyers", sector: "Office & Admin", employment: 168680, medianWage: 36550, aiExposure: 9.4, outlook: "Decline", education: "High school" },
  { soc: "43-9022", title: "Word Processors and Typists", sector: "Office & Admin", employment: 53390, medianWage: 44660, aiExposure: 9.3, outlook: "Decline", education: "High school" },
  { soc: "43-9031", title: "Desktop Publishers", sector: "Office & Admin", employment: 9770, medianWage: 50990, aiExposure: 9.0, outlook: "Decline", education: "Associate's" },
  { soc: "43-9041", title: "Insurance Claims and Policy Processing Clerks", sector: "Office & Admin", employment: 257560, medianWage: 43710, aiExposure: 9.1, outlook: "Decline", education: "High school" },
  { soc: "43-9061", title: "Office Clerks, General", sector: "Office & Admin", employment: 2857020, medianWage: 36500, aiExposure: 8.7, outlook: "Decline", education: "High school" },
  { soc: "43-9071", title: "Office Machine Operators, Except Computer", sector: "Office & Admin", employment: 14890, medianWage: 36080, aiExposure: 8.2, outlook: "Decline", education: "High school" },
  { soc: "45-1011", title: "First-Line Supervisors of Farming, Fishing, and Forestry Workers", sector: "Agriculture", employment: 47550, medianWage: 48770, aiExposure: 2.8, outlook: "Decline", education: "High school" },
  { soc: "45-2092", title: "Farmworkers and Laborers, Crop, Nursery, and Greenhouse", sector: "Agriculture", employment: 310320, medianWage: 29510, aiExposure: 2.1, outlook: "Average", education: "High school" },
  { soc: "47-1011", title: "First-Line Supervisors of Construction Trades Workers", sector: "Construction", employment: 632670, medianWage: 71260, aiExposure: 3.5, outlook: "Average", education: "High school" },
  { soc: "47-2011", title: "Boilermakers", sector: "Construction", employment: 14990, medianWage: 64290, aiExposure: 3.1, outlook: "Average", education: "High school" },
  { soc: "47-2021", title: "Brickmasons and Blockmasons", sector: "Construction", employment: 70640, medianWage: 60400, aiExposure: 2.3, outlook: "Average", education: "High school" },
  { soc: "47-2031", title: "Carpenters", sector: "Construction", employment: 936400, medianWage: 55990, aiExposure: 2.4, outlook: "Average", education: "High school" },
  { soc: "47-2041", title: "Carpet Installers", sector: "Construction", employment: 22360, medianWage: 45870, aiExposure: 2.1, outlook: "Average", education: "High school" },
  { soc: "47-2051", title: "Cement Masons and Concrete Finishers", sector: "Construction", employment: 178330, medianWage: 50690, aiExposure: 2.2, outlook: "Average", education: "High school" },
  { soc: "47-2061", title: "Construction Laborers", sector: "Construction", employment: 1397350, medianWage: 42160, aiExposure: 2.8, outlook: "Average", education: "High school" },
  { soc: "47-2071", title: "Paving, Surfacing, and Tamping Equipment Operators", sector: "Construction", employment: 69930, medianWage: 48990, aiExposure: 3.2, outlook: "Average", education: "High school" },
  { soc: "47-2073", title: "Operating Engineers and Other Construction Equipment Operators", sector: "Construction", employment: 411920, medianWage: 56090, aiExposure: 3.8, outlook: "Average", education: "High school" },
  { soc: "47-2082", title: "Tapers", sector: "Construction", employment: 41790, medianWage: 55710, aiExposure: 2.0, outlook: "Average", education: "High school" },
  { soc: "47-2111", title: "Electricians", sector: "Construction", employment: 715230, medianWage: 60040, aiExposure: 3.1, outlook: "Faster", education: "High school" },
  { soc: "47-2121", title: "Glaziers", sector: "Construction", employment: 47730, medianWage: 48420, aiExposure: 2.4, outlook: "Average", education: "High school" },
  { soc: "47-2131", title: "Insulation Workers", sector: "Construction", employment: 53470, medianWage: 44310, aiExposure: 2.1, outlook: "Average", education: "High school" },
  { soc: "47-2141", title: "Painters, Construction and Maintenance", sector: "Construction", employment: 491460, medianWage: 45590, aiExposure: 2.5, outlook: "Average", education: "High school" },
  { soc: "47-2151", title: "Pipelayers, Plumbers, Pipefitters, and Steamfitters", sector: "Construction", employment: 508870, medianWage: 59880, aiExposure: 2.9, outlook: "Average", education: "High school" },
  { soc: "47-2161", title: "Plasterers and Stucco Masons", sector: "Construction", employment: 28730, medianWage: 49850, aiExposure: 2.2, outlook: "Average", education: "High school" },
  { soc: "47-2171", title: "Reinforcing Iron and Rebar Workers", sector: "Construction", employment: 17440, medianWage: 62090, aiExposure: 2.1, outlook: "Average", education: "High school" },
  { soc: "47-2181", title: "Roofers", sector: "Construction", employment: 171150, medianWage: 46010, aiExposure: 2.0, outlook: "Average", education: "High school" },
  { soc: "47-2211", title: "Sheet Metal Workers", sector: "Construction", employment: 135370, medianWage: 55930, aiExposure: 3.3, outlook: "Average", education: "High school" },
  { soc: "47-2221", title: "Structural Iron and Steel Workers", sector: "Construction", employment: 82540, medianWage: 59520, aiExposure: 2.4, outlook: "Average", education: "High school" },
  { soc: "49-1011", title: "First-Line Supervisors of Mechanics, Installers, and Repairers", sector: "Installation & Repair", employment: 492230, medianWage: 72240, aiExposure: 3.8, outlook: "Average", education: "High school" },
  { soc: "49-2021", title: "Radio, Cellular, and Tower Equipment Installers and Repairers", sector: "Installation & Repair", employment: 15980, medianWage: 59280, aiExposure: 4.2, outlook: "Average", education: "High school" },
  { soc: "49-2022", title: "Telecommunications Equipment Installers and Repairers", sector: "Installation & Repair", employment: 213290, medianWage: 59200, aiExposure: 5.3, outlook: "Average", education: "Some college" },
  { soc: "49-2092", title: "Electric Motor, Power Tool, and Related Repairers", sector: "Installation & Repair", employment: 28230, medianWage: 50820, aiExposure: 3.4, outlook: "Average", education: "High school" },
  { soc: "49-2093", title: "Electrical and Electronics Installers and Repairers, Transportation Equipment", sector: "Installation & Repair", employment: 13820, medianWage: 61460, aiExposure: 3.9, outlook: "Average", education: "High school" },
  { soc: "49-3011", title: "Aircraft Mechanics and Service Technicians", sector: "Installation & Repair", employment: 129640, medianWage: 70440, aiExposure: 4.1, outlook: "Average", education: "Certificate" },
  { soc: "49-3021", title: "Automotive Body and Related Repairers", sector: "Installation & Repair", employment: 149230, medianWage: 47870, aiExposure: 3.6, outlook: "Decline", education: "High school" },
  { soc: "49-3023", title: "Automotive Service Technicians and Mechanics", sector: "Installation & Repair", employment: 763680, medianWage: 46880, aiExposure: 4.8, outlook: "Average", education: "Certificate" },
  { soc: "49-3031", title: "Bus and Truck Mechanics and Diesel Engine Specialists", sector: "Installation & Repair", employment: 289530, medianWage: 56260, aiExposure: 4.2, outlook: "Average", education: "Certificate" },
  { soc: "49-3041", title: "Farm Equipment Mechanics and Service Technicians", sector: "Installation & Repair", employment: 37620, medianWage: 45760, aiExposure: 3.4, outlook: "Average", education: "High school" },
  { soc: "49-3042", title: "Mobile Heavy Equipment Mechanics, Except Engines", sector: "Installation & Repair", employment: 109400, medianWage: 57480, aiExposure: 3.8, outlook: "Average", education: "High school" },
  { soc: "49-3051", title: "Motorboat Mechanics and Service Technicians", sector: "Installation & Repair", employment: 18430, medianWage: 42820, aiExposure: 2.9, outlook: "Average", education: "High school" },
  { soc: "49-3053", title: "Outdoor Power Equipment and Other Small Engine Mechanics", sector: "Installation & Repair", employment: 37530, medianWage: 38320, aiExposure: 2.6, outlook: "Average", education: "High school" },
  { soc: "49-9012", title: "Control and Valve Installers and Repairers", sector: "Installation & Repair", employment: 43340, medianWage: 60090, aiExposure: 4.1, outlook: "Average", education: "High school" },
  { soc: "49-9021", title: "Heating, Air Conditioning, and Refrigeration Mechanics and Installers", sector: "Installation & Repair", employment: 396200, medianWage: 57300, aiExposure: 3.5, outlook: "Faster", education: "Certificate" },
  { soc: "49-9041", title: "Industrial Machinery Mechanics", sector: "Installation & Repair", employment: 380060, medianWage: 58100, aiExposure: 4.7, outlook: "Faster", education: "High school" },
  { soc: "49-9071", title: "Maintenance and Repair Workers, General", sector: "Maintenance", employment: 1432830, medianWage: 42760, aiExposure: 3.2, outlook: "Average", education: "High school" },
  { soc: "49-9094", title: "Locksmiths and Safe Repairers", sector: "Installation & Repair", employment: 28200, medianWage: 44800, aiExposure: 3.7, outlook: "Average", education: "High school" },
  { soc: "51-1011", title: "First-Line Supervisors of Production and Operating Workers", sector: "Production", employment: 668580, medianWage: 63060, aiExposure: 5.1, outlook: "Average", education: "High school" },
  { soc: "51-2011", title: "Aircraft Structure, Surfaces, Rigging, and Systems Assemblers", sector: "Production", employment: 32040, medianWage: 57820, aiExposure: 4.3, outlook: "Average", education: "High school" },
  { soc: "51-2021", title: "Coil Winders, Tapers, and Finishers", sector: "Production", employment: 11300, medianWage: 41350, aiExposure: 5.8, outlook: "Decline", education: "High school" },
  { soc: "51-2022", title: "Electrical and Electronic Equipment Assemblers", sector: "Production", employment: 137980, medianWage: 38380, aiExposure: 6.2, outlook: "Decline", education: "High school" },
  { soc: "51-2031", title: "Engine and Other Machine Assemblers", sector: "Production", employment: 21800, medianWage: 52210, aiExposure: 5.4, outlook: "Decline", education: "High school" },
  { soc: "51-2041", title: "Structural Metal Fabricators and Fitters", sector: "Production", employment: 74770, medianWage: 47680, aiExposure: 4.2, outlook: "Average", education: "High school" },
  { soc: "51-2091", title: "Fiberglass Laminators and Fabricators", sector: "Production", employment: 11450, medianWage: 40290, aiExposure: 3.4, outlook: "Average", education: "High school" },
  { soc: "51-2092", title: "Team Assemblers", sector: "Production", employment: 1202930, medianWage: 38800, aiExposure: 5.9, outlook: "Average", education: "High school" },
  { soc: "51-3011", title: "Bakers", sector: "Production", employment: 196000, medianWage: 32870, aiExposure: 3.1, outlook: "Average", education: "High school" },
  { soc: "51-3021", title: "Butchers and Meat, Poultry, and Fish Cutters and Trimmers", sector: "Production", employment: 168910, medianWage: 36430, aiExposure: 3.4, outlook: "Average", education: "High school" },
  { soc: "51-4011", title: "Computer Numerically Controlled Tool Operators and Programmers", sector: "Production", employment: 161990, medianWage: 47200, aiExposure: 6.3, outlook: "Average", education: "High school" },
  { soc: "51-4021", title: "Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic", sector: "Production", employment: 79260, medianWage: 44040, aiExposure: 5.7, outlook: "Average", education: "High school" },
  { soc: "51-4031", title: "Cutting, Punching, and Press Machine Setters, Operators, and Tenders", sector: "Production", employment: 157310, medianWage: 40680, aiExposure: 5.4, outlook: "Decline", education: "High school" },
  { soc: "51-4041", title: "Machinists", sector: "Production", employment: 357950, medianWage: 49250, aiExposure: 5.2, outlook: "Average", education: "High school" },
  { soc: "51-4121", title: "Welders, Cutters, Solderers, and Brazers", sector: "Production", employment: 422020, medianWage: 47010, aiExposure: 4.6, outlook: "Average", education: "High school" },
  { soc: "51-5111", title: "Prepress Technicians and Workers", sector: "Production", employment: 22910, medianWage: 45820, aiExposure: 8.6, outlook: "Decline", education: "Associate's" },
  { soc: "51-5112", title: "Printing Press Operators", sector: "Production", employment: 105030, medianWage: 41660, aiExposure: 7.4, outlook: "Decline", education: "High school" },
  { soc: "51-6011", title: "Laundry and Dry-Cleaning Workers", sector: "Production", employment: 185590, medianWage: 28600, aiExposure: 3.8, outlook: "Average", education: "High school" },
  { soc: "51-6021", title: "Pressers, Textile, Garment, and Related Materials", sector: "Production", employment: 51680, medianWage: 29220, aiExposure: 4.1, outlook: "Decline", education: "High school" },
  { soc: "51-6031", title: "Sewing Machine Operators", sector: "Production", employment: 157610, medianWage: 31850, aiExposure: 4.8, outlook: "Decline", education: "High school" },
  { soc: "51-6041", title: "Shoe and Leather Workers and Repairers", sector: "Production", employment: 17560, medianWage: 31420, aiExposure: 2.8, outlook: "Decline", education: "High school" },
  { soc: "51-6051", title: "Sewers, Hand", sector: "Production", employment: 12670, medianWage: 30670, aiExposure: 2.4, outlook: "Decline", education: "High school" },
  { soc: "51-7011", title: "Cabinetmakers and Bench Carpenters", sector: "Production", employment: 134750, medianWage: 41250, aiExposure: 2.9, outlook: "Average", education: "High school" },
  { soc: "51-7021", title: "Furniture Finishers", sector: "Production", employment: 16060, medianWage: 38760, aiExposure: 2.7, outlook: "Average", education: "High school" },
  { soc: "53-1041", title: "Aircraft Cargo Handling Supervisors", sector: "Transportation", employment: 9930, medianWage: 56740, aiExposure: 4.6, outlook: "Average", education: "High school" },
  { soc: "53-1048", title: "First-Line Supervisors of Transportation and Material-Moving Workers", sector: "Transportation", employment: 213630, medianWage: 61420, aiExposure: 4.4, outlook: "Average", education: "High school" },
  { soc: "53-2011", title: "Airline Pilots, Copilots, and Flight Engineers", sector: "Transportation", employment: 103180, medianWage: 202180, aiExposure: 4.2, outlook: "Faster", education: "Bachelor's" },
  { soc: "53-2012", title: "Commercial Pilots", sector: "Transportation", employment: 40350, medianWage: 99640, aiExposure: 4.8, outlook: "Faster", education: "Certificate" },
  { soc: "53-3011", title: "Ambulance Drivers and Attendants", sector: "Transportation", employment: 18360, medianWage: 29110, aiExposure: 3.1, outlook: "Average", education: "High school" },
  { soc: "53-3032", title: "Heavy and Tractor-Trailer Truck Drivers", sector: "Transportation", employment: 2047300, medianWage: 49920, aiExposure: 7.1, outlook: "Average", education: "High school" },
  { soc: "53-3033", title: "Light Truck Drivers", sector: "Transportation", employment: 1282230, medianWage: 40260, aiExposure: 6.4, outlook: "Average", education: "High school" },
  { soc: "53-3041", title: "Taxi Drivers and Chauffeurs", sector: "Transportation", employment: 171590, medianWage: 30990, aiExposure: 7.6, outlook: "Average", education: "High school" },
  { soc: "53-3051", title: "Bus Drivers, School", sector: "Transportation", employment: 494620, medianWage: 40400, aiExposure: 5.8, outlook: "Average", education: "High school" },
  { soc: "53-3052", title: "Bus Drivers, Transit and Intercity", sector: "Transportation", employment: 167980, medianWage: 50320, aiExposure: 6.2, outlook: "Average", education: "High school" },
  { soc: "53-4011", title: "Locomotive Engineers and Operators", sector: "Transportation", employment: 35040, medianWage: 71890, aiExposure: 5.3, outlook: "Average", education: "High school" },
  { soc: "53-6011", title: "Bridge and Lock Tenders", sector: "Transportation", employment: 2560, medianWage: 51290, aiExposure: 4.1, outlook: "Decline", education: "High school" },
  { soc: "53-7011", title: "Conveyor Operators and Tenders", sector: "Transportation", employment: 29960, medianWage: 37080, aiExposure: 6.3, outlook: "Decline", education: "High school" },
  { soc: "53-7021", title: "Crane and Tower Operators", sector: "Transportation", employment: 47930, medianWage: 61900, aiExposure: 5.1, outlook: "Average", education: "High school" },
  { soc: "53-7041", title: "Hoist and Winch Operators", sector: "Transportation", employment: 2880, medianWage: 58970, aiExposure: 4.8, outlook: "Average", education: "High school" },
  { soc: "53-7051", title: "Industrial Truck and Tractor Operators", sector: "Transportation", employment: 659810, medianWage: 39210, aiExposure: 6.8, outlook: "Decline", education: "High school" },
  { soc: "53-7062", title: "Laborers and Freight, Stock, and Material Movers, Hand", sector: "Transportation", employment: 3328200, medianWage: 34730, aiExposure: 5.9, outlook: "Average", education: "High school" },
  { soc: "53-7065", title: "Stockers and Order Fillers", sector: "Transportation", employment: 3050360, medianWage: 32450, aiExposure: 6.7, outlook: "Average", education: "High school" },
  { soc: "53-7072", title: "Pump Operators, Except Wellhead Pumpers", sector: "Transportation", employment: 10380, medianWage: 54760, aiExposure: 4.4, outlook: "Decline", education: "High school" },
];

// ---- Derived aggregates ----

export const TOTAL_EMPLOYMENT = OCCUPATIONS.reduce((sum, o) => sum + o.employment, 0);

export const HIGH_EXPOSURE = OCCUPATIONS.filter(o => o.aiExposure >= 7);
export const HIGH_EXPOSURE_EMPLOYMENT = HIGH_EXPOSURE.reduce((sum, o) => sum + o.employment, 0);

export const SECTORS = [...new Set(OCCUPATIONS.map(o => o.sector))].sort();

export function byExposureTier() {
  return {
    critical: OCCUPATIONS.filter(o => o.aiExposure >= 8),
    high:     OCCUPATIONS.filter(o => o.aiExposure >= 6 && o.aiExposure < 8),
    medium:   OCCUPATIONS.filter(o => o.aiExposure >= 4 && o.aiExposure < 6),
    low:      OCCUPATIONS.filter(o => o.aiExposure < 4),
  };
}

export function bySector() {
  return OCCUPATIONS.reduce((acc, o) => {
    (acc[o.sector] = acc[o.sector] || []).push(o);
    return acc;
  }, {});
}

export function topAtRisk(n = 25) {
  return [...OCCUPATIONS].sort((a, b) => b.aiExposure - a.aiExposure).slice(0, n);
}

export function mostSafe(n = 10) {
  return [...OCCUPATIONS].sort((a, b) => a.aiExposure - b.aiExposure).slice(0, n);
}

export function bySOC(soc) {
  return OCCUPATIONS.find(o => o.soc === soc) || null;
}

export function weightedAvgExposure() {
  const totalEmp = OCCUPATIONS.reduce((s, o) => s + o.employment, 0);
  return OCCUPATIONS.reduce((s, o) => s + (o.aiExposure * o.employment / totalEmp), 0);
}
